# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

<p><img alt="Colaboratory logo" height="45px" src="/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>

<h1>What is Colaboratory?</h1>

Colaboratory, or "Colab" for short, allows you to write and execute Python in your browser, with 
- Zero configuration required
- Free access to GPUs
- Easy sharing

Whether you're a **student**, a **data scientist** or an **AI researcher**, Colab can make your work easier. Watch [Introduction to Colab](https://www.youtube.com/watch?v=inN8seMm7UI) to learn more, or just get started below!

## **Getting started**

The document you are reading is not a static web page, but an interactive environment called a **Colab notebook** that lets you write and execute code.

For example, here is a **code cell** with a short Python script that computes a value, stores it in a variable, and prints the result:
"""

seconds_in_a_day = 24 * 60 * 60
seconds_in_a_day

"""To execute the code in the above cell, select it with a click and then either press the play button to the left of the code, or use the keyboard shortcut "Command/Ctrl+Enter". To edit the code, just click the cell and start editing.

Variables that you define in one cell can later be used in other cells:
"""

seconds_in_a_week = 7 * seconds_in_a_day
seconds_in_a_week

"""Colab notebooks allow you to combine **executable code** and **rich text** in a single document, along with **images**, **HTML**, **LaTeX** and more. When you create your own Colab notebooks, they are stored in your Google Drive account. You can easily share your Colab notebooks with co-workers or friends, allowing them to comment on your notebooks or even edit them. To learn more, see [Overview of Colab](/notebooks/basic_features_overview.ipynb). To create a new Colab notebook you can use the File menu above, or use the following link: [create a new Colab notebook](http://colab.research.google.com#create=true).

Colab notebooks are Jupyter notebooks that are hosted by Colab. To learn more about the Jupyter project, see [jupyter.org](https://www.jupyter.org).

## Data science

With Colab you can harness the full power of popular Python libraries to analyze and visualize data. The code cell below uses **numpy** to generate some random data, and uses **matplotlib** to visualize it. To edit the code, just click the cell and start editing.
"""

import numpy as np
from matplotlib import pyplot as plt

ys = 200 + np.random.randn(100)
x = [x for x in range(len(ys))]

plt.plot(x, ys, '-')
plt.fill_between(x, ys, 195, where=(ys > 195), facecolor='g', alpha=0.6)

plt.title("Sample Visualization")
plt.show()

"""You can import your own data into Colab notebooks from your Google Drive account, including from spreadsheets, as well as from Github and many other sources. To learn more about importing data, and how Colab can be used for data science, see the links below under [Working with Data](#working-with-data).

## Machine learning

With Colab you can import an image dataset, train an image classifier on it, and evaluate the model, all in just [a few lines of code](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb). Colab notebooks execute code on Google's cloud servers, meaning you can leverage the power of Google hardware, including [GPUs and TPUs](#using-accelerated-hardware), regardless of the power of your machine. All you need is a browser.

Colab is used extensively in the machine learning community with applications including:
- Getting started with TensorFlow
- Developing and training neural networks
- Experimenting with TPUs
- Disseminating AI research
- Creating tutorials

To see sample Colab notebooks that demonstrate machine learning applications, see the [machine learning examples](#machine-learning-examples) below.

## More Resources

### Working with Notebooks in Colab
- [Overview of Colaboratory](/notebooks/basic_features_overview.ipynb)
- [Guide to Markdown](/notebooks/markdown_guide.ipynb)
- [Importing libraries and installing dependencies](/notebooks/snippets/importing_libraries.ipynb)
- [Saving and loading notebooks in GitHub](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb)
- [Interactive forms](/notebooks/forms.ipynb)
- [Interactive widgets](/notebooks/widgets.ipynb)
- <img src="/img/new.png" height="20px" align="left" hspace="4px" alt="New"></img>
 [TensorFlow 2 in Colab](/notebooks/tensorflow_version.ipynb)

<a name="working-with-data"></a>
### Working with Data
- [Loading data: Drive, Sheets, and Google Cloud Storage](/notebooks/io.ipynb) 
- [Charts: visualizing data](/notebooks/charts.ipynb)
- [Getting started with BigQuery](/notebooks/bigquery.ipynb)

### Machine Learning Crash Course
These are a few of the notebooks from Google's online Machine Learning course. See the [full course website](https://developers.google.com/machine-learning/crash-course/) for more.
- [Intro to Pandas](/notebooks/mlcc/intro_to_pandas.ipynb)
- [Tensorflow concepts](/notebooks/mlcc/tensorflow_programming_concepts.ipynb)
- [First steps with TensorFlow](/notebooks/mlcc/first_steps_with_tensor_flow.ipynb)
- [Intro to neural nets](/notebooks/mlcc/intro_to_neural_nets.ipynb)
- [Intro to sparse data and embeddings](/notebooks/mlcc/intro_to_sparse_data_and_embeddings.ipynb)

<a name="using-accelerated-hardware"></a>
### Using Accelerated Hardware
- [TensorFlow with GPUs](/notebooks/gpu.ipynb)
- [TensorFlow with TPUs](/notebooks/tpu.ipynb)

<a name="machine-learning-examples"></a>

## Machine Learning Examples

To see end-to-end examples of the interactive machine learning analyses that Colaboratory makes possible, check out these  tutorials using models from [TensorFlow Hub](https://tfhub.dev).

A few featured examples:

- [Retraining an Image Classifier](https://tensorflow.org/hub/tutorials/tf2_image_retraining): Build a Keras model on top of a pre-trained image classifier to distinguish flowers.
- [Text Classification](https://tensorflow.org/hub/tutorials/tf2_text_classification): Classify IMDB movie reviews as either *positive* or *negative*.
- [Style Transfer](https://tensorflow.org/hub/tutorials/tf2_arbitrary_image_stylization): Use deep learning to transfer style between images.
- [Multilingual Universal Sentence Encoder Q&A](https://tensorflow.org/hub/tutorials/retrieval_with_tf_hub_universal_encoder_qa): Use a machine learning model to answer questions from the SQuAD dataset.
- [Video Interpolation](https://tensorflow.org/hub/tutorials/tweening_conv3d): Predict what happened in a video between the first and the last frame.
"""

import numpy as np
import pandas as pd
import datetime
from scipy.stats import skew
from scipy.fftpack import fft
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_validate,train_test_split,StratifiedKFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
import pickle


input_file_path = input("Enter the test file name/path")
print("Entered file path",input_file_path)
Test_Data = pd.read_csv(input_file_path)

Feature_Matrix = pd.DataFrame()

# Feature 1 - Windowed Mean (for 30 min interval)
win_size=6
total_vals = Test_Data.shape[1]-win_size
for index in range(0, total_vals, win_size):
    dm = Test_Data.iloc[:, index:index + win_size].mean(axis=1)
    Feature_Matrix['Mean ' + str(index)] = dm

#print(Feature_Matrix.shape)

    
# Feature 2 - Windowed Standard Deviation (for 30 min interval)
win_size=6
total_vals = Test_Data.shape[1]-win_size
for index in range(0, total_vals, win_size):
    dstd = Test_Data.iloc[:, index:index + win_size].std(axis=1)
    Feature_Matrix['Std_deviation ' + str(index)] = dstd
        
#print(Feature_Matrix.shape)

# Feature 3 - Fast Fourier Transform
FFT = pd.DataFrame()
print("before applying fft")
def calculate_fft_vals(row):
    FFT_abs = abs(fft(row))
    FFT_abs.sort()
    return np.flip(FFT_abs)[0:8]

FFT['FFT_vals'] = Test_Data.apply(lambda row: calculate_fft_vals(row), axis=1)
FFT_Vals= pd.DataFrame(FFT.FFT_vals.tolist(), columns=['FFT1', 'FFT2', 'FFT3', 'FFT4', 'FFT5', 'FFT6', 'FFT7','FFT8'],index=FFT.FFT_vals.index)
Feature_Matrix = pd.concat([Feature_Matrix,FFT_Vals],axis=1)
    
#print(Feature_Matrix.shape)
    
    
# Feature 4 - Max of CGM Velocity 
Velocity_Data = pd.DataFrame()
win_size=6
total_vals=Test_Data.shape[1]-win_size

for index in range(0, total_vals):
    dv = Test_Data.iloc[:, index + win_size] - Test_Data.iloc[:, index]
    Velocity_Data['vel'+str(index)] = dv

Feature_Matrix['Max CGM Vel']=Velocity_Data.max(axis = 1,skipna=True)
    
#print(Feature_Matrix.shape)
    
    
# Feature 5 - Skewness
def calculate_skewness(series):
    series_counts = series.value_counts()
    skewness_vals = skew(series_counts)
    return skewness_vals

Feature_Matrix['skewness'] = Test_Data.apply(lambda row: calculate_skewness(row), axis=1)
#print("final shape")
#print(Feature_Matrix.shape)

Feature_Matrix  = StandardScaler().fit_transform(Feature_Matrix)

K=5
print("------ Predicting class using KNN model--------")
for i in range(1,K+1):
    handler = open("KNN"+str(i)+".model","rb")
    model = pickle.load(handler)
    pd.DataFrame(model.predict(Feature_Matrix)).to_csv("KNN"+str(i)+"output.csv",index=False,header=False)
    handler.close()
    print("Generated output for KNN"+str(i)+" in KNN"+str(i)+"output.csv")
    

print("------ Predicting class using SVM model--------")
handler = open("SVC.model","rb")
model = pickle.load(handler)
pd.DataFrame(model.predict(Feature_Matrix)).to_csv("SVCoutput.csv",index=False,header=False)
handler.close()
print("Generated output for SVC in SVCoutput.csv")